
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#

[[override]]
name="github.com/golang/glog"
revision="23def4e6c14b4da8ac2ed8007337bc5eb5007998"

[[override]]
name="k8s.io/api"
version="kubernetes-1.10.0"

[[override]]
name="k8s.io/apiextensions-apiserver"
version="kubernetes-1.10.1"

[[override]]
name="k8s.io/apimachinery"
version="kubernetes-1.10.0"

[[override]]
name="k8s.io/client-go"
version="kubernetes-1.10.1"
