
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
[[override]]
name="k8s.io/api"
version="kubernetes-1.10.0"

[[override]]
name="k8s.io/apiextensions-apiserver"
version="kubernetes-1.10.1"

[[override]]
name="k8s.io/apimachinery"
version="kubernetes-1.10.0"

[[override]]
name="k8s.io/client-go"
version="kubernetes-1.10.1"

[[override]]
name="github.com/openshift/client-go"
branch="release-3.10"

[[override]]
name="github.com/sirupsen/logrus"
version="v1.0.5"

[[override]]
name="github.com/spf13/cobra"
version="0.0.1"

[[override]]
name="github.com/spf13/pflag"
version="1.0.0"
